### ISSUE TITLE
release new version?

### ISSUE THREAD

**Issue by k-okada** [longjie/ps4eye#14]
it seems we have several update. can I release new version?

**Comment by longjie** [comment]
Yes, I want to release 0.0.4. How can you do that?

**Comment by k-okada** [comment]
that's super easy, just to type

```
bloom-release ps4eye -t hydro -r hydro
```

but you need to write access to https://github.com/tork-a/ps4eye-release.git, so if you want to do that by your self, we can give you such access, but just to write new issue at tork-a/ps4eye-release would be ok for us. we launched tork for this purpose.

at this time I did by my self, see https://github.com/ros/rosdistro/pull/7684

**Comment by longjie** [comment]
Thanks! I will write new issue when we need to release new version.
