### ISSUE TITLE
What is the issue of /dev/video0 not showing up?

### ISSUE THREAD

**Issue by robograffitti** [longjie/ps4eye#17]
I finally could get ps4eye launched.
However, I struggled with the issue of not getting /dev/video0.
The original repository tells us to blacklist uvc things, but it doesn't work.

Instead, I installed some of the uvc packages from the list below, shown by apt-cache search uvc:
y-tanaka@y-tanaka-W541:~/ros/hydro/src/ps4eye$ apt-cache search uvc
guvcview - GTK+ base UVC Viewer
uvccapture - USB UVC Video Class snapshot software
uvcdynctrl - Command line tool to control v4l2 devices
uvcdynctrl-data - Command line tool to control v4l2 devices - data files
uvcdynctrl-dbg - Debug Symbols for uvcdynctrl
luvcview - USB Video クラスキャプチャ
ros-hydro-libuvc - USB Video Class driver library
ros-hydro-libuvc-camera - USB Video Class camera driver
ros-hydro-libuvc-ros - libuvc_ros metapackage
ros-hydro-uvc-camera - A collection of node(let)s that stream images from USB cameras (UVC) and provide CameraInfo messages to consumers. Includes a two-camera node that provides rough synchronization for stereo vision. Currently uses the base driver from Morgan Quigley's uvc_cam package

In my memory, I installed guvcview, uvcapture, luvcview, ros-hydro-libuvc-*, and ros-hydro-uvc-camera. Which one is really necessary for ps4eye? If it's known, it should be written in the READ.md.

**Comment by longjie** [comment]
Thank you, we need to write correct dependency in package.xml.
ps4eye uses gstreamer framework, so I guess ros-hydro-gscam is the correct dependency.

Beware gscam is not released for indigo, that's why ps4eye package have not released in indigo.

**Comment by longjie** [comment]
Don't you have any /dev/video\* file? If so, the package dependency may not be the reason.

Please check:
- The kernel version (> 3.17) and the camera connected to the USB 3.0 port
- check the system can detect the USB device(05a9:058a or 05a9:0580). Do:

```
$ lsusb
```

If you don't see any USB devices on the bus when you pluged the camera, the reason would be hardware(soldering) or USB 3.0 driver. 

Sometimes I encounterd that I need to plug and unplug serveral times before the system recognize the device.

Good luck,
