### ISSUE TITLE
Parameters for ROS stereo_img_proc

### ISSUE THREAD

**Issue by kfechter** [longjie/ps4eye#18]
What parameters should I use for ROS stereo_img_proc? When I use the command outlined in the readme, I just get a few splotches and it doesn't detect a person in front of the cameras like shown in the demo.

**Comment by longjie** [comment]
Try stereo camera calibration described as: 
http://wiki.ros.org/camera_calibration/Tutorials/StereoCalibration

I didn't tune the stereo matching parameter for the demo, but you may need to tune stereo parameter as:
http://wiki.ros.org/stereo_image_proc/Tutorials/ChoosingGoodStereoParameters

**Comment by kfechter** [comment]
ah, yeah I realized I had forgotten to calibrate. I need to find a good area for calibration and get the proper grid. 

I tried it in a lab, but there wasn't enough space. It's a little better, but still not fully there.

**Comment by kfechter** [comment]
Seems to work well now, the camera still has issues, but positive its not this software causing it.

**Comment by longjie** [comment]
Thanks for reporting! @kfechter
