### ISSUE TITLE
class gscam/GSCamNodelet does not exist

### ISSUE THREAD

**Issue by kylelindgren** [longjie/ps4eye#25]
I am running 14.04 with linux kernel 3.17.3 and ROS Indigo. I can get images with Cheese from the ps4 camera but running stereo.launch gives the following:

`[ERROR] [1466968441.274647095]: Failed to load nodelet [/gscam_driver] of type [gscam/GSCamNodelet] even after refreshing the cache: According to the loaded plugin descriptions the class gscam/GSCamNodelet with base class type nodelet::Nodelet does not exist.`

**Full output:**
kylelindgren@kyle509:~/git/ps4eye_ws$ roslaunch ps4eye stereo.launch DEVICE:=/dev/video1 viewer:=true
... logging to /home/kylelindgren/.ros/log/75fdbbca-3bc4-11e6-9b90-c4850850139c/roslaunch-kyle509-13846.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://kyle509:40258/
# SUMMARY

PARAMETERS
- /camera_info_publisher/left_file_name: /home/kylelindgre...
- /camera_info_publisher/right_file_name: /home/kylelindgre...
- /gscam_driver/camera_info_url: file:///home/kyle...
- /gscam_driver/camera_name: default
- /gscam_driver/frame_id: /ps4eye_frame
- /gscam_driver/gscam_config: v4l2src device=/d...
- /gscam_driver/sync_sink: True
- /rosdistro: indigo
- /rosversion: 1.11.19
- /split_left/camera_info_url: file:///home/kyle...
- /split_left/camera_name: left
- /split_left/height: 400
- /split_left/queue_size: 10
- /split_left/width: 640
- /split_left/x_offset: 688
- /split_left/y_offset: 0
- /split_right/camera_info_url: file:///home/kyle...
- /split_right/camera_name: right
- /split_right/height: 400
- /split_right/queue_size: 10
- /split_right/width: 640
- /split_right/x_offset: 48
- /split_right/y_offset: 0

NODES
  /stereo/left/
    debayer (nodelet/nodelet)
    rectify_color (nodelet/nodelet)
    rectify_mono (nodelet/nodelet)
  /stereo/
    disparity (nodelet/nodelet)
    point_cloud2 (nodelet/nodelet)
  /stereo/right/
    debayer (nodelet/nodelet)
    rectify_color (nodelet/nodelet)
    rectify_mono (nodelet/nodelet)
  /
    camera_info_publisher (ps4eye/camera_info_publisher.py)
    camera_transform (tf/static_transform_publisher)
    gscam_driver (nodelet/nodelet)
    manager (nodelet/nodelet)
    split_left (nodelet/nodelet)
    split_right (nodelet/nodelet)
    stereo_view (image_view/stereo_view)

ROS_MASTER_URI=http://localhost:11311

core service [/rosout] found
process[manager-1]: started with pid [13864]
process[gscam_driver-2]: started with pid [13865]
process[split_right-3]: started with pid [13866]
process[split_left-4]: started with pid [13867]
process[camera_transform-5]: started with pid [13874]
[ INFO] [1466968440.269713483]: Loading nodelet /gscam_driver of type gscam/GSCamNodelet to manager manager with the following remappings:
process[camera_info_publisher-6]: started with pid [13885]
[ INFO] [1466968440.277637803]: waitForService: Service [/manager/load_nodelet] has not been advertised, waiting...
process[stereo/left/debayer-7]: started with pid [13896]
process[stereo/left/rectify_mono-8]: started with pid [13907]
process[stereo/left/rectify_color-9]: started with pid [13915]
process[stereo/right/debayer-10]: started with pid [13919]
process[stereo/right/rectify_mono-11]: started with pid [13935]
process[stereo/right/rectify_color-12]: started with pid [13940]
process[stereo/disparity-13]: started with pid [13942]
process[stereo/point_cloud2-14]: started with pid [13949]
process[stereo_view-15]: started with pid [13958]
[ INFO] [1466968440.333973983]: Initializing nodelet with 8 worker threads.
[ INFO] [1466968440.360157523]: waitForService: Service [/manager/load_nodelet] is now available.
[ERROR] [1466968441.274647095]: Failed to load nodelet [/gscam_driver] of type [gscam/GSCamNodelet] even after refreshing the cache: According to the loaded plugin descriptions the class gscam/GSCamNodelet with base class type nodelet::Nodelet does not exist. Declared types are  camshift/camshift contour_moments/contour_moments convex_hull/convex_hull depth_image_proc/convert_metric depth_image_proc/crop_foremost depth_image_proc/disparity depth_image_proc/point_cloud_xyz depth_image_proc/point_cloud_xyz_radial depth_image_proc/point_cloud_xyzi depth_image_proc/point_cloud_xyzi_radial depth_image_proc/point_cloud_xyzrgb depth_image_proc/register edge_detection/edge_detection face_detection/face_detection fback_flow/fback_flow find_contours/find_contours general_contours/general_contours goodfeature_track/goodfeature_track hough_circles/hough_circles hough_lines/hough_lines image_proc/crop_decimate image_proc/crop_nonZero image_proc/debayer image_proc/rectify image_rotate/image_rotate image_view/disparity image_view/image lk_flow/lk_flow nodelet_tutorial_math/Plus pcl/BAGReader pcl/BoundaryEstimation pcl/ConvexHull2D pcl/CropBox pcl/EuclideanClusterExtraction pcl/ExtractIndices pcl/ExtractPolygonalPrismData pcl/FPFHEstimation pcl/FPFHEstimationOMP pcl/MomentInvariantsEstimation pcl/MovingLeastSquares pcl/NodeletDEMUX pcl/NodeletMUX pcl/NormalEstimation pcl/NormalEstimationOMP pcl/NormalEstimationTBB pcl/PCDReader pcl/PCDWriter pcl/PFHEstimation pcl/PassThrough pcl/PointCloudConcatenateDataSynchronizer pcl/PointCloudConcatenateFieldsSynchronizer pcl/PrincipalCurvaturesEstimation pcl/ProjectInliers pcl/RadiusOutlierRemoval pcl/SACSegmentation pcl/SACSegmentationFromNormals pcl/SHOTEstimation pcl/SHOTEstimationOMP pcl/SegmentDifferences pcl/StatisticalOutlierRemoval pcl/VFHEstimation pcl/VoxelGrid people_detect/people_detect phase_corr/phase_corr pointcloud_to_laserscan/pointcloud_to_laserscan_nodelet segment_objects/segment_objects simple_compressed_example/simple_compressed_example simple_example/simple_example simple_flow/simple_flow stereo_image_proc/disparity stereo_image_proc/point_cloud2 watershed_segmentation/watershed_segmentation
[ERROR] [1466968441.274759691]: The error before refreshing the cache was: According to the loaded plugin descriptions the class gscam/GSCamNodelet with base class type nodelet::Nodelet does not exist. Declared types are  camshift/camshift contour_moments/contour_moments convex_hull/convex_hull depth_image_proc/convert_metric depth_image_proc/crop_foremost depth_image_proc/disparity depth_image_proc/point_cloud_xyz depth_image_proc/point_cloud_xyz_radial depth_image_proc/point_cloud_xyzi depth_image_proc/point_cloud_xyzi_radial depth_image_proc/point_cloud_xyzrgb depth_image_proc/register edge_detection/edge_detection face_detection/face_detection fback_flow/fback_flow find_contours/find_contours general_contours/general_contours goodfeature_track/goodfeature_track hough_circles/hough_circles hough_lines/hough_lines image_proc/crop_decimate image_proc/crop_nonZero image_proc/debayer image_proc/rectify image_rotate/image_rotate image_view/disparity image_view/image lk_flow/lk_flow nodelet_tutorial_math/Plus pcl/BAGReader pcl/BoundaryEstimation pcl/ConvexHull2D pcl/CropBox pcl/EuclideanClusterExtraction pcl/ExtractIndices pcl/ExtractPolygonalPrismData pcl/FPFHEstimation pcl/FPFHEstimationOMP pcl/MomentInvariantsEstimation pcl/MovingLeastSquares pcl/NodeletDEMUX pcl/NodeletMUX pcl/NormalEstimation pcl/NormalEstimationOMP pcl/NormalEstimationTBB pcl/PCDReader pcl/PCDWriter pcl/PFHEstimation pcl/PassThrough pcl/PointCloudConcatenateDataSynchronizer pcl/PointCloudConcatenateFieldsSynchronizer pcl/PrincipalCurvaturesEstimation pcl/ProjectInliers pcl/RadiusOutlierRemoval pcl/SACSegmentation pcl/SACSegmentationFromNormals pcl/SHOTEstimation pcl/SHOTEstimationOMP pcl/SegmentDifferences pcl/StatisticalOutlierRemoval pcl/VFHEstimation pcl/VoxelGrid people_detect/people_detect phase_corr/phase_corr pointcloud_to_laserscan/pointcloud_to_laserscan_nodelet segment_objects/segment_objects simple_compressed_example/simple_compressed_example simple_example/simple_example simple_flow/simple_flow stereo_image_proc/disparity stereo_image_proc/point_cloud2 watershed_segmentation/watershed_segmentation
[FATAL] [1466968441.274946586]: Service call failed!
[gscam_driver-2] process has died [pid 13865, exit code 255, cmd /opt/ros/indigo/lib/nodelet/nodelet load gscam/GSCamNodelet manager __name:=gscam_driver __log:=/home/kylelindgren/.ros/log/75fdbbca-3bc4-11e6-9b90-c4850850139c/gscam_driver-2.log].
log file: /home/kylelindgren/.ros/log/75fdbbca-3bc4-11e6-9b90-c4850850139c/gscam_driver-2*.log

Any advice would be greatly appreciated.

**Comment by k-okada** [comment]
you need to install https://github.com/ros-drivers/gscam in your catkin workspace, I think

**Comment by kylelindgren** [comment]
Installing gscam in the workspace and running 
`apt-get install libgstreamer0.10-dev libgstreamer-plugins-base0.10-dev`
before catkin_make did the trick. Thanks for the help!
