### ISSUE TITLE
ps4eye under Ubuntu 16.04 

### ISSUE THREAD

**Issue by eugenebartosh** [longjie/ps4eye#27]
Ubuntu 16.04 LTS kernel 4.4.0-38-generic
1. Firmware applied via phyton script - "PS4 camera firmware uploaded and device reset"
2. lsusb report: http://i.prntscr.com/cc566ce1068540cbb34de4e85eaced7c.png
3. guvcview reports: 

eugene@EBUB:~/ps4eye/script$ guvcview
GUVCVIEW: version 2.0.2
V4L2_CORE: (UVCIOC_CTRL_MAP) Error: No such file or directory
V4L2_CORE: (UVCIOC_CTRL_MAP) Error: No such file or directory
V4L2_CORE: (UVCIOC_CTRL_MAP) Error: No such file or directory
V4L2_CORE: (UVCIOC_CTRL_MAP) Error: No such file or directory
V4L2_CORE: (UVCIOC_CTRL_MAP) Error: No such file or directory
V4L2_CORE: (UVCIOC_CTRL_MAP) Error: No such file or directory
V4L2_CORE: (UVCIOC_CTRL_MAP) Error: No such file or directory
V4L2_CORE: (UVCIOC_CTRL_MAP) Error: No such file or directory
V4L2_CORE: (UVCIOC_CTRL_MAP) Error: No such file or directory
GUVCVIEW: couldn't get a valid audio context for the selected api - disabling audio
libv4l2: error turning on stream: No space left on device
V4L2_CORE: (VIDIOC_STREAMON) Unable to start stream: No space left on device 
V4L2_CORE: (get_v4l2_frame) video stream must be started first
V4L2_CORE: (get_v4l2_frame) video stream must be started first
V4L2_CORE: (get_v4l2_frame) video stream must be started first
V4L2_CORE: (get_v4l2_frame) video stream must be started first

Thank you in advance!
Eugene

**Comment by longjie** [comment]
I've got same error with my MacBook Air + Ubuntu 16.04 LTS kernel 4.4.0-38-generic. 
Sorry to say, I have no idea to solve this problem right now.
Do you have any idea, users?

**Comment by eugenebartosh** [comment]
Would you please say what kernel / OS will support it for sure? I am considering to setup older platform.

**Comment by longjie** [comment]
Please see #23 for the reported working environments.
With my pc, newer kernels somehow dont work (see also #19).

The hacked firmware may be the reason of dependency on the environment. Unfortunately I can't do anything with the firmware.

Thanks,

**Comment by eugenebartosh** [comment]
I tried multiple kernels including 3.17.3 and 3.19.0 as recommended, but the outcome is always the same. 
And I tested on 2 computers - PC box and laptop. 
Both PC and laptop are based on i7 26xx CPUs. 
I connected camera to all possible USB3 ports, using different buses/hubs.
Do you think I should try some other hardware?

Thanks, 
Eugene

**Comment by eugenebartosh** [comment]
I have just received my Jetson TK1 and tried on it - PS4 Camera works like a charm there. 
So these problems might appear hardware dependent. 
Trying different hardware solved problem in my case.

**Comment by longjie** [comment]
Thank you for reporting!
