### ISSUE TITLE
Release request

### ISSUE THREAD

**Issue by furushchev** [longjie/ps4eye#32]
Hi, I found this nice package which is not yet released as `deb`.
It'd be very nice if this package is released on indigo (if possible though EOL) / kinetic.
Thank you!

**Comment by longjie** [comment]
Hi, thanks,

@k-okada  tried to release this to indigo, jade, kinetic and lunar a year ago.
I believe it blocked by gscam package, which was not released at that time.

https://github.com/ros/rosdistro/pull/14882#issuecomment-300023642

**Comment by k-okada** [comment]
released on both indigo/kinetic https://github.com/ros/rosdistro/pull/18439

**Comment by longjie** [comment]
BTW, [this comment](https://github.com/bigboss-ps3dev/PS4EYECam/issues/1#issuecomment-284658830) will help if your ps4eye in newer kernel.
